{% set name = "agate-stats" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d93d919774e1655ada54cf7bf096f39d0522d4eb6eb569cf3896533226927b9a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - agate >=1.5.0

test:
  imports:
    - agatestats
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://agate-stats.readthedocs.org/
  summary: agate-stats adds additional statistical methods to agate.
  license: MIT
  license_file: COPYING
  doc_url: http://agate-stats.readthedocs.org/
  dev_url: https://github.com/wireservice/agate-stats

extra:
  recipe-maintainers:
    - pmlandwehr
